require('dotenv').config();
const mongoose = require('mongoose');
const LabTest = require('./models/LabTest');

const TESTS = [
  // ── BLOOD TESTS ─────────────────────────────────────────────────────────────
  { name: 'Complete Blood Count (CBC)', category: 'Blood Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 349, estimatedReportTime: '6-8 hours', normalRange: 'RBC 4.5-5.5 M/uL; WBC 4500-11000/uL; Hb 12-17 g/dL', preparationInstructions: 'Fast 8-12 hours. Drink water freely.', description: 'Evaluates RBC, WBC, haemoglobin, haematocrit, and platelets. Screens for anaemia, infection, and blood disorders.', tags: ['CBC','blood','routine','haemoglobin'] },
  { name: 'Erythrocyte Sedimentation Rate (ESR)', category: 'Blood Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 149, estimatedReportTime: '2 hours', normalRange: 'Male: 0-15 mm/hr; Female: 0-20 mm/hr', preparationInstructions: 'No special preparation.', description: 'Measures how quickly RBCs settle. Elevated in inflammation, infection, autoimmune disease, and cancer.' },
  { name: 'C-Reactive Protein (CRP)', category: 'Blood Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 399, estimatedReportTime: '6 hours', normalRange: 'Normal < 6 mg/L; hs-CRP < 1 mg/L', preparationInstructions: 'No fasting required.', description: 'Measures inflammation marker produced by the liver. Elevated in bacterial infections, autoimmune disorders, and cardiovascular disease.', tags: ['CRP','inflammation'] },
  { name: 'Blood Group & Rh Factor', category: 'Blood Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 149, estimatedReportTime: '2 hours', normalRange: 'ABO group + Rh Positive/Negative', preparationInstructions: 'No preparation needed.', description: 'Determines ABO blood group (A, B, AB, O) and Rh factor. Essential before transfusions and surgery.', tags: ['blood group','Rh','ABO'] },
  { name: 'Peripheral Blood Smear', category: 'Blood Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 299, estimatedReportTime: '4-6 hours', normalRange: 'Normal morphology of RBC/WBC/Platelets', preparationInstructions: 'No fasting required.', description: 'Microscopic examination of blood cells to detect abnormal morphology, malaria parasites, and leukaemia.' },

  // ── URINE TESTS ─────────────────────────────────────────────────────────────
  { name: 'Urine Routine & Microscopy', category: 'Urine Tests', sampleType: 'Urine', popularityFlag: 'Common', price: 199, estimatedReportTime: '2-4 hours', normalRange: 'pH 4.5-8; Protein: Nil; Glucose: Nil; RBC < 2/HPF', preparationInstructions: 'Collect mid-stream first-morning sample in sterile container.', description: 'Complete urine examination: colour, pH, protein, glucose, ketones, and microscopy for cells and casts.', tags: ['urine','UTI','kidney'] },
  { name: 'Urine Culture & Sensitivity', category: 'Urine Tests', sampleType: 'Urine', popularityFlag: 'Common', price: 499, estimatedReportTime: '48-72 hours', normalRange: 'No growth (sterile)', preparationInstructions: 'Clean catch mid-stream sample. Avoid antibiotics 72 hrs prior.', description: 'Grows bacteria from urine to identify organism causing UTI and determines appropriate antibiotic.' },
  { name: '24-Hour Urine Protein', category: 'Urine Tests', sampleType: 'Urine', popularityFlag: 'Advanced', price: 399, estimatedReportTime: '24 hours', normalRange: 'Normal < 150 mg/24 hrs', preparationInstructions: 'Collect ALL urine for 24 hours. Refrigerate container.', description: 'Measures total protein lost in urine over 24 hours to assess kidney disease severity.' },
  { name: 'Urine Microalbumin', category: 'Urine Tests', sampleType: 'Urine', popularityFlag: 'Common', price: 499, estimatedReportTime: '6 hours', normalRange: 'Normal < 30 mg/g creatinine', preparationInstructions: 'Random spot urine or first morning sample.', description: 'Detects tiny amounts of albumin in urine, an early marker of diabetic kidney disease.', tags: ['microalbumin','diabetes','kidney'] },
  { name: 'Stool Routine Examination', category: 'Urine Tests', sampleType: 'Stool', popularityFlag: 'Common', price: 249, estimatedReportTime: '24 hours', normalRange: 'No parasites, no occult blood', preparationInstructions: 'Collect fresh stool in sterile container. Avoid toilet water.', description: 'Examines stool for parasites, blood, mucus, and bacteria. Detects infections and GI disorders.' },

  // ── DIABETES TESTS ──────────────────────────────────────────────────────────
  { name: 'Fasting Blood Glucose (FBG)', category: 'Diabetes Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 99, estimatedReportTime: '2-4 hours', normalRange: 'Normal 70-100 mg/dL; Pre-DM 100-125; DM >= 126', preparationInstructions: 'Fast strictly 8-10 hours. Only plain water allowed.', description: 'Measures blood sugar after overnight fasting to screen and diagnose diabetes and pre-diabetes.', tags: ['glucose','diabetes','fasting'] },
  { name: 'Postprandial Blood Glucose (PPBG)', category: 'Diabetes Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 99, estimatedReportTime: '2 hours', normalRange: 'Normal < 140 mg/dL; Diabetes >= 200 mg/dL', preparationInstructions: 'Eat a normal meal; sample drawn exactly 2 hours after first bite.', description: 'Measures blood sugar 2 hours after a meal to assess glucose management.' },
  { name: 'HbA1c (Glycated Haemoglobin)', category: 'Diabetes Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 399, estimatedReportTime: '4-6 hours', normalRange: 'Normal < 5.7%; Pre-DM 5.7-6.4%; DM >= 6.5%', preparationInstructions: 'No fasting required. Can be done any time of day.', description: 'Reflects average blood sugar over the past 3 months. Gold standard for diabetes monitoring.', tags: ['HbA1c','glycated','diabetes'] },
  { name: 'Random Blood Glucose', category: 'Diabetes Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 79, estimatedReportTime: '30 minutes', normalRange: 'Normal < 140 mg/dL; Concern >= 200 with symptoms', preparationInstructions: 'No preparation needed. Any time test.', description: 'Quick screening test measuring blood sugar at any time regardless of last meal.' },
  { name: 'Insulin Fasting & Postprandial', category: 'Diabetes Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 799, estimatedReportTime: '24 hours', normalRange: 'Fasting 2-25 mIU/L; PP 18-55 mIU/L', preparationInstructions: 'Fast 8-10 hours. Second sample 2 hrs after 75g glucose load.', description: 'Measures insulin secretion capacity and resistance to distinguish Type 1 vs Type 2 diabetes.' },
  { name: 'OGTT (Oral Glucose Tolerance Test)', category: 'Diabetes Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 499, estimatedReportTime: '4 hours', normalRange: '2hr: Normal < 140; Pre-DM 140-199; DM >= 200 mg/dL', preparationInstructions: 'Fast 8-12 hrs. 3 blood draws over 2 hours after glucose drink.', description: '75g glucose load test with multiple blood draws. Diagnoses gestational diabetes and pre-diabetes.' },

  // ── THYROID TESTS ───────────────────────────────────────────────────────────
  { name: 'TSH (Thyroid Stimulating Hormone)', category: 'Thyroid Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 299, estimatedReportTime: '6-24 hours', normalRange: '0.4-4.0 mIU/L', preparationInstructions: 'No fasting needed. Best drawn in morning.', description: 'Primary screening test for thyroid disorders. Elevated TSH = hypothyroidism; Low TSH = hyperthyroidism.', tags: ['TSH','thyroid'] },
  { name: 'Free T3 (Triiodothyronine)', category: 'Thyroid Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 349, estimatedReportTime: '6-24 hours', normalRange: '2.0-4.4 pg/mL', preparationInstructions: 'No fasting. Inform lab of any thyroid medications.', description: 'Measures active thyroid hormone T3. Useful in diagnosing hyperthyroidism and T3 toxicosis.' },
  { name: 'Free T4 (Thyroxine)', category: 'Thyroid Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 349, estimatedReportTime: '6-24 hours', normalRange: '0.8-1.8 ng/dL', preparationInstructions: 'No fasting required.', description: 'Measures thyroxine levels. Helps differentiate primary from secondary hypothyroidism.' },
  { name: 'Thyroid Profile (T3, T4, TSH)', category: 'Thyroid Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 599, estimatedReportTime: '24 hours', normalRange: 'TSH 0.4-4.0; T3 80-200 ng/dL; T4 5-12 ug/dL', preparationInstructions: 'No fasting required. Inform doctor of thyroid medications.', description: 'Complete thyroid panel measuring T3, T4, and TSH for comprehensive thyroid function assessment.', tags: ['thyroid profile','TSH','T3','T4'] },
  { name: 'Anti-TPO Antibodies', category: 'Thyroid Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 699, estimatedReportTime: '24-48 hours', normalRange: 'Normal < 34 IU/mL', preparationInstructions: 'No fasting required.', description: 'Detects autoimmune thyroid disease (Hashimoto thyroiditis and Graves disease).' },

  // ── LIVER FUNCTION TESTS ────────────────────────────────────────────────────
  { name: 'Liver Function Test (LFT)', category: 'Liver Function Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 549, estimatedReportTime: '6-24 hours', normalRange: 'ALT 7-40 U/L; AST 10-40 U/L; Total Bilirubin 0.1-1.2 mg/dL', preparationInstructions: 'Fast 8-10 hrs. Avoid alcohol 24 hrs prior.', description: 'Complete liver panel: ALT, AST, ALP, bilirubin, albumin, total protein. Assesses liver health.', tags: ['LFT','liver','enzymes'] },
  { name: 'SGPT / ALT (Liver Enzyme)', category: 'Liver Function Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 199, estimatedReportTime: '4-6 hours', normalRange: '7-40 U/L', preparationInstructions: 'Fast 8 hours preferred.', description: 'Alanine aminotransferase, the most specific liver enzyme. Elevated primarily in liver cell damage.' },
  { name: 'Serum Bilirubin (Total & Direct)', category: 'Liver Function Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 249, estimatedReportTime: '4-6 hours', normalRange: 'Total 0.1-1.2 mg/dL; Direct 0-0.3 mg/dL', preparationInstructions: 'Fast 4-8 hours.', description: 'Measures bilirubin to diagnose jaundice, liver disease, bile duct obstruction, and haemolytic anaemia.' },
  { name: 'Hepatitis B Surface Antigen (HBsAg)', category: 'Liver Function Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 349, estimatedReportTime: '4-6 hours', normalRange: 'Non-reactive (Negative)', preparationInstructions: 'No fasting required.', description: 'Detects active Hepatitis B infection. Positive indicates current infection or carrier state.', tags: ['HBsAg','hepatitis B'] },
  { name: 'Hepatitis C Antibody (Anti-HCV)', category: 'Liver Function Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 499, estimatedReportTime: '4-6 hours', normalRange: 'Non-reactive (Negative)', preparationInstructions: 'No fasting required.', description: 'Detects antibodies to Hepatitis C virus, screening for past or present HCV infection.' },

  // ── KIDNEY FUNCTION TESTS ───────────────────────────────────────────────────
  { name: 'Kidney Function Test (KFT)', category: 'Kidney Function Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 449, estimatedReportTime: '6-24 hours', normalRange: 'Creatinine 0.6-1.2 mg/dL; Urea 7-20 mg/dL; Uric Acid 2.4-7.2 mg/dL', preparationInstructions: 'Fast 8-10 hrs. Stay hydrated with water.', description: 'Complete renal panel: creatinine, urea, uric acid, electrolytes. Evaluates kidney filtering efficiency.', tags: ['KFT','kidney','creatinine'] },
  { name: 'Serum Creatinine', category: 'Kidney Function Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 149, estimatedReportTime: '4-6 hours', normalRange: 'Male 0.7-1.2 mg/dL; Female 0.5-1.0 mg/dL', preparationInstructions: 'Fast 8 hours. Avoid heavy meat meals.', description: 'Most common kidney marker. Elevated creatinine indicates reduced glomerular filtration.' },
  { name: 'eGFR (Estimated Glomerular Filtration Rate)', category: 'Kidney Function Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 249, estimatedReportTime: '6 hours', normalRange: 'Normal >= 90 mL/min/1.73m2; CKD Stage 5 < 15', preparationInstructions: 'Fast 8 hours.', description: 'Calculates how well kidneys filter waste. Stages chronic kidney disease (CKD Stage 1-5).' },
  { name: 'Serum Uric Acid', category: 'Kidney Function Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 199, estimatedReportTime: '4 hours', normalRange: 'Male 3.4-7.2 mg/dL; Female 2.4-6.0 mg/dL', preparationInstructions: 'Fast 4-8 hours. Avoid purine-rich foods prior.', description: 'Measures uric acid levels. High levels cause gout and contribute to kidney stones.' },

  // ── LIPID PROFILE TESTS ─────────────────────────────────────────────────────
  { name: 'Lipid Profile', category: 'Lipid Profile Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 499, estimatedReportTime: '6-24 hours', normalRange: 'Total < 200; HDL > 40 (M)/50 (F); LDL < 100; Trig < 150 mg/dL', preparationInstructions: 'Fast 10-12 hrs. No alcohol 24 hrs. Avoid fatty food.', description: 'Complete cholesterol panel: Total, HDL, LDL, VLDL cholesterol and triglycerides. Cardiovascular risk.', tags: ['lipid','cholesterol','cardiac'] },
  { name: 'LDL Cholesterol (Direct)', category: 'Lipid Profile Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 399, estimatedReportTime: '4-6 hours', normalRange: 'Optimal < 100 mg/dL; High >= 160 mg/dL', preparationInstructions: 'Fast 12 hours. No alcohol.', description: 'Measures LDL (bad cholesterol) directly without calculation. Most accurate for CV risk management.' },
  { name: 'HDL Cholesterol', category: 'Lipid Profile Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 199, estimatedReportTime: '4-6 hours', normalRange: 'Optimal > 60 mg/dL; Risk < 40 mg/dL', preparationInstructions: 'Fast 10-12 hours.', description: 'HDL is the protective (good) cholesterol. Low HDL is an independent risk factor for heart disease.' },
  { name: 'Triglycerides', category: 'Lipid Profile Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 199, estimatedReportTime: '4-6 hours', normalRange: 'Normal < 150 mg/dL; High 200-499; Very High >= 500', preparationInstructions: 'Fast strictly 10-12 hours.', description: 'Measures fat in blood from dietary intake and liver production. High triglycerides = metabolic syndrome.' },

  // ── VITAMIN & MINERAL TESTS ─────────────────────────────────────────────────
  { name: 'Vitamin D (25-OH)', category: 'Vitamin & Mineral Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 799, estimatedReportTime: '24-48 hours', normalRange: 'Deficiency < 20 ng/mL; Sufficient 20-50 ng/mL', preparationInstructions: 'No fasting required. Can be done anytime.', description: 'Measures 25-hydroxyvitamin D. Deficiency causes rickets, osteoporosis, and immune dysfunction.', tags: ['vitamin D','bone','immunity'] },
  { name: 'Vitamin B12 (Cobalamin)', category: 'Vitamin & Mineral Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 699, estimatedReportTime: '24 hours', normalRange: 'Normal 200-900 pg/mL; Deficiency < 200 pg/mL', preparationInstructions: 'No fasting required.', description: 'Measures B12 levels. Deficiency causes megaloblastic anaemia and neuropathy. Common in vegetarians.', tags: ['vitamin B12','anaemia','vegan'] },
  { name: 'Folate / Folic Acid', category: 'Vitamin & Mineral Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 599, estimatedReportTime: '24 hours', normalRange: 'Normal 2.7-17.0 ng/mL', preparationInstructions: 'Fast 4-6 hours.', description: 'Essential for DNA synthesis. Deficiency causes neural tube defects in pregnancy and megaloblastic anaemia.' },
  { name: 'Serum Iron & TIBC', category: 'Vitamin & Mineral Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 499, estimatedReportTime: '24 hours', normalRange: 'Serum Iron 60-170 ug/dL; TIBC 240-450 ug/dL', preparationInstructions: 'Fast 8-12 hours. Morning sample preferred.', description: 'Measures serum iron, transferrin, and total iron binding capacity. Diagnoses iron deficiency anaemia.' },
  { name: 'Serum Calcium', category: 'Vitamin & Mineral Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 199, estimatedReportTime: '4-6 hours', normalRange: '8.5-10.5 mg/dL', preparationInstructions: 'No fasting needed.', description: 'Measures calcium levels. Abnormal calcium causes muscle cramps, kidney stones, and arrhythmias.' },
  { name: 'Zinc Level', category: 'Vitamin & Mineral Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 649, estimatedReportTime: '24-48 hours', normalRange: '60-120 ug/dL', preparationInstructions: 'Fast 8 hours. Morning sample for accuracy.', description: 'Measures zinc deficiency linked to immune suppression, delayed wound healing, and growth problems.' },

  // ── HORMONE TESTS ───────────────────────────────────────────────────────────
  { name: 'Testosterone (Total)', category: 'Hormone Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 699, estimatedReportTime: '24 hours', normalRange: 'Male 300-1000 ng/dL; Female 15-70 ng/dL', preparationInstructions: 'Blood drawn 7-10am (morning). Fast 8 hours.', description: 'Total testosterone in blood. Low levels cause hypogonadism, reduced libido, fatigue, and infertility.', tags: ['testosterone','hormone','fertility'] },
  { name: 'FSH & LH (Fertility Panel)', category: 'Hormone Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 799, estimatedReportTime: '24 hours', normalRange: 'FSH follicular 2.5-10 mIU/mL; LH mid-cycle 20-105 mIU/mL', preparationInstructions: 'Day 2-3 of menstrual cycle for women. Fast 8 hrs.', description: 'Key hormones for evaluating menstrual disorders, menopause, and male/female infertility.' },
  { name: 'Prolactin', category: 'Hormone Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 599, estimatedReportTime: '24 hours', normalRange: 'Non-pregnant female 2-29 ng/mL; Male 2-18 ng/mL', preparationInstructions: 'Blood drawn 2-3 hours after waking.', description: 'Measures prolactin. Elevated in pituitary tumours causing galactorrhoea and menstrual irregularity.' },
  { name: 'Cortisol (Morning)', category: 'Hormone Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 699, estimatedReportTime: '24 hours', normalRange: 'Morning 6-23 ug/dL; Afternoon 3-12 ug/dL', preparationInstructions: 'Blood drawn 6-10am fasting. Avoid physical stress.', description: 'Stress hormone from adrenal gland. Evaluates adrenal function; abnormal in Cushings or Addisons disease.' },
  { name: 'AMH (Anti-Mullerian Hormone)', category: 'Hormone Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 1499, estimatedReportTime: '48 hours', normalRange: 'Good > 1.5 ng/mL; Low < 0.5 ng/mL', preparationInstructions: 'Any day of cycle. No fasting required.', description: 'Best ovarian reserve marker for fertility assessment. Guides IVF protocols and predicts menopause timing.' },

  // ── CARDIAC TESTS ───────────────────────────────────────────────────────────
  { name: 'ECG / Electrocardiogram', category: 'Cardiac Tests', sampleType: 'N/A', popularityFlag: 'Common', price: 350, estimatedReportTime: '30 minutes', normalRange: 'Normal sinus rhythm; PR 0.12-0.20s; QRS < 0.12s', preparationInstructions: 'Avoid heavy exercise 30 min before. No oils on chest.', description: 'Records electrical activity of the heart. Detects arrhythmias, heart attacks, and chamber enlargement.', tags: ['ECG','heart','arrhythmia'] },
  { name: 'Troponin I / T (Cardiac)', category: 'Cardiac Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 999, estimatedReportTime: '4 hours', normalRange: 'Normal < 0.04 ng/mL', preparationInstructions: 'No fasting required. Emergency test.', description: 'Most sensitive marker for heart muscle damage. Elevated within 3-6 hours of a heart attack.' },
  { name: 'BNP / NT-proBNP (Heart Failure)', category: 'Cardiac Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 1199, estimatedReportTime: '4-6 hours', normalRange: 'BNP < 100 pg/mL normal; Heart failure > 400 pg/mL', preparationInstructions: 'No fasting required.', description: 'Brain Natriuretic Peptide released by stressed heart. Gold standard for diagnosing heart failure.' },
  { name: 'Homocysteine', category: 'Cardiac Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 899, estimatedReportTime: '24-48 hours', normalRange: 'Normal 5-15 umol/L; High risk > 15', preparationInstructions: 'Fast 8-12 hours.', description: 'Elevated homocysteine is an independent risk factor for coronary artery disease and stroke.' },
  { name: 'Lipoprotein (a) [Lp(a)]', category: 'Cardiac Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 1099, estimatedReportTime: '24-48 hours', normalRange: 'Normal < 30 mg/dL; High risk > 50 mg/dL', preparationInstructions: 'Fast 10-12 hours.', description: 'Genetically determined lipid particle that is an independent cardiac risk factor.' },
  { name: '2D Echocardiography', category: 'Cardiac Tests', sampleType: 'N/A', popularityFlag: 'Common', price: 1499, estimatedReportTime: '30-45 minutes', normalRange: 'EF > 55%; Normal valve function', preparationInstructions: 'No fasting required. Avoid heavy exercise.', description: 'Ultrasound of heart showing chambers, valves, and ejection fraction. Primary cardiac structural evaluation.', tags: ['echo','heart','EF','valve'] },

  // ── INFECTION & DISEASE TESTS ────────────────────────────────────────────────
  { name: 'Dengue NS1 Antigen + IgM/IgG', category: 'Infection & Disease Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 799, estimatedReportTime: '4-6 hours', normalRange: 'Negative (Non-reactive)', preparationInstructions: 'No fasting. Best during fever days 1-5.', description: 'Combo test for dengue fever. NS1 detects acute infection; IgM/IgG for current or past infection.', tags: ['dengue','NS1','fever'] },
  { name: 'Malaria (Rapid Antigen Test)', category: 'Infection & Disease Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 349, estimatedReportTime: '30 minutes', normalRange: 'Negative', preparationInstructions: 'Sample during fever spike.', description: 'Rapid card test detecting Plasmodium falciparum and P. vivax antigens in 20 minutes.' },
  { name: 'COVID-19 RT-PCR', category: 'Infection & Disease Tests', sampleType: 'Swab', popularityFlag: 'Common', price: 499, estimatedReportTime: '6-24 hours', normalRange: 'Not Detected', preparationInstructions: 'No eating/drinking/smoking 30 min before. Nasopharyngeal swab.', description: 'Gold standard test for COVID-19. Amplifies SARS-CoV-2 RNA from nasopharyngeal swab.', tags: ['COVID','RTPCR'] },
  { name: 'Typhoid (Widal Test)', category: 'Infection & Disease Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 249, estimatedReportTime: '4-6 hours', normalRange: 'Negative or O-antigen < 1:80', preparationInstructions: 'Sample best after 7-10 days of illness. No fasting.', description: 'Detects antibodies to Salmonella typhi and paratyphi for typhoid fever diagnosis.' },
  { name: 'HIV 1 & 2 Antibody Test', category: 'Infection & Disease Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 499, estimatedReportTime: '4-6 hours', normalRange: 'Non-reactive (Negative)', preparationInstructions: 'No fasting required. Counselling provided.', description: 'Detects antibodies to HIV-1 and HIV-2. Recommended for all adults as routine health screening.', tags: ['HIV','AIDS'] },
  { name: 'Chikungunya IgM Antibody', category: 'Infection & Disease Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 599, estimatedReportTime: '24 hours', normalRange: 'Non-reactive (Negative)', preparationInstructions: 'No fasting. Best during acute phase.', description: 'Detects IgM antibodies to Chikungunya virus. Causes joint pain and fever.' },
  { name: 'Procalcitonin (PCT)', category: 'Infection & Disease Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 1199, estimatedReportTime: '4-6 hours', normalRange: 'Normal < 0.1 ng/mL; Sepsis > 2 ng/mL', preparationInstructions: 'No fasting required.', description: 'Highly specific bacterial infection marker. Used to guide antibiotic therapy and diagnose sepsis.' },
  { name: 'Blood Culture & Sensitivity', category: 'Infection & Disease Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 999, estimatedReportTime: '3-5 days', normalRange: 'No growth (Sterile)', preparationInstructions: 'Sample during fever spike. Multiple draws needed.', description: 'Grows bacteria from blood to diagnose bacteraemia or sepsis and identify appropriate antibiotics.' },

  // ── CANCER SCREENING TESTS ───────────────────────────────────────────────────
  { name: 'PSA (Prostate Specific Antigen)', category: 'Cancer Screening Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 699, estimatedReportTime: '24 hours', normalRange: 'Age 40-50 < 2.5 ng/mL; Age 50+ < 4 ng/mL', preparationInstructions: 'No ejaculation or vigorous exercise 24 hrs before.', description: 'Screens for prostate cancer and BPH. Elevated PSA requires further evaluation with biopsy.', tags: ['PSA','prostate','cancer'] },
  { name: 'CA-125 (Ovarian Cancer Marker)', category: 'Cancer Screening Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 899, estimatedReportTime: '24-48 hours', normalRange: 'Normal < 35 U/mL', preparationInstructions: 'Not recommended during menstruation.', description: 'Elevated in ovarian cancer, endometriosis, and pregnancy. Used to monitor ovarian cancer treatment.' },
  { name: 'CEA (Carcinoembryonic Antigen)', category: 'Cancer Screening Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 899, estimatedReportTime: '24-48 hours', normalRange: 'Non-smoker < 2.5 ng/mL; Smoker < 5.0 ng/mL', preparationInstructions: 'No fasting required.', description: 'Tumour marker primarily for colorectal cancer. Also elevated in lung, breast, and GI cancers.', tags: ['CEA','colorectal','cancer'] },
  { name: 'AFP (Alpha Fetoprotein)', category: 'Cancer Screening Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 799, estimatedReportTime: '24-48 hours', normalRange: 'Normal adult < 10 ng/mL', preparationInstructions: 'No fasting required.', description: 'Elevated in hepatocellular carcinoma (liver cancer) and germ cell tumours. Also used in prenatal screening.' },
  { name: 'CA 19-9 (Pancreatic Marker)', category: 'Cancer Screening Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 999, estimatedReportTime: '24-48 hours', normalRange: 'Normal < 37 U/mL', preparationInstructions: 'No fasting required.', description: 'Tumour marker for pancreatic cancer and cholangiocarcinoma. Used to monitor treatment response.' },

  // ── ALLERGY TESTS ────────────────────────────────────────────────────────────
  { name: 'IgE Total (Allergy Screen)', category: 'Allergy Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 499, estimatedReportTime: '24 hours', normalRange: 'Normal < 150 IU/mL (age-dependent)', preparationInstructions: 'No fasting required.', description: 'Measures total immunoglobulin E. Elevated in allergic conditions like asthma, eczema, and food allergy.', tags: ['IgE','allergy','asthma'] },
  { name: 'Food Allergy Panel (IgE)', category: 'Allergy Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 2499, estimatedReportTime: '3-5 days', normalRange: 'Specific IgE class < 0.35 kU/L = Negative', preparationInstructions: 'No fasting. Continue regular diet.', description: 'Tests IgE-mediated food allergies to common foods: milk, eggs, wheat, peanut, fish, soy, tree nuts.' },
  { name: 'Inhalant Allergy Panel', category: 'Allergy Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 2499, estimatedReportTime: '3-5 days', normalRange: 'Specific IgE class < 0.35 kU/L = Negative', preparationInstructions: 'No fasting required.', description: 'Tests sensitivity to dust mites, pollens, mold, pet dander, and cockroach allergens.' },
  { name: 'ANA (Antinuclear Antibody)', category: 'Allergy Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 699, estimatedReportTime: '24-48 hours', normalRange: 'Negative: titre < 1:80', preparationInstructions: 'No fasting required.', description: 'Screens for autoimmune diseases like lupus (SLE), Sjogrens syndrome, and rheumatoid arthritis.', tags: ['ANA','lupus','autoimmune'] },
  { name: 'Rheumatoid Factor (RF)', category: 'Allergy Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 399, estimatedReportTime: '24 hours', normalRange: 'Normal < 14 IU/mL', preparationInstructions: 'No fasting required.', description: 'Detects rheumatoid factor antibodies. Positive in rheumatoid arthritis and autoimmune conditions.' },

  // ── PREGNANCY TESTS ──────────────────────────────────────────────────────────
  { name: 'Serum Beta-hCG (Pregnancy)', category: 'Pregnancy Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 399, estimatedReportTime: '4-6 hours', normalRange: 'Non-pregnant < 5 mIU/mL; Pregnancy rises from 5 mIU/mL', preparationInstructions: 'No fasting required.', description: 'Quantitative pregnancy hormone test. More sensitive than urine tests; detects pregnancy within 8-10 days.', tags: ['pregnancy','hCG','beta-hCG'] },
  { name: 'TORCH Profile', category: 'Pregnancy Tests', sampleType: 'Blood', popularityFlag: 'Common', price: 1999, estimatedReportTime: '48-72 hours', normalRange: 'All non-reactive or IgG only', preparationInstructions: 'No fasting required.', description: 'Screens for infections harmful in pregnancy: Toxoplasma, Rubella, CMV, Herpes. Critical for antenatal care.', tags: ['TORCH','pregnancy','rubella','CMV'] },
  { name: 'Down Syndrome Screening (Double Marker)', category: 'Pregnancy Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 1799, estimatedReportTime: '48-72 hours', normalRange: 'Low risk < 1:250; High risk > 1:250', preparationInstructions: 'No fasting. Done with NT ultrasound at 11-14 weeks.', description: 'First trimester screening measuring PAPP-A and free beta-hCG to assess Down syndrome risk.' },
  { name: 'Antenatal Profile (Full)', category: 'Pregnancy Tests', sampleType: 'Multiple', popularityFlag: 'Common', price: 1499, estimatedReportTime: '24-48 hours', normalRange: 'Multiple parameters', preparationInstructions: 'Fast 8-10 hours for glucose component.', description: 'Complete first trimester screen: CBC, Blood group, HIV, HBsAg, VDRL, urine routine, blood glucose.' },

  // ── GENETIC TESTS ────────────────────────────────────────────────────────────
  { name: 'Karyotyping', category: 'Genetic Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 3999, estimatedReportTime: '10-14 days', normalRange: 'Normal: 46,XX (female) or 46,XY (male)', preparationInstructions: 'No fasting. Special cytogenetics blood tube required.', description: 'Examines chromosomes for abnormalities. Used for Down syndrome, Turner, and Klinefelter diagnosis.', tags: ['karyotype','chromosome','genetic'] },
  { name: 'BRCA1 & BRCA2 Gene Test', category: 'Genetic Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 12999, estimatedReportTime: '15-21 days', normalRange: 'No pathogenic variant detected', preparationInstructions: 'No fasting. Genetic counselling recommended.', description: 'Detects mutations in BRCA1/2 genes associated with hereditary breast and ovarian cancer.' },
  { name: 'Thalassaemia Screening', category: 'Genetic Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 1999, estimatedReportTime: '5-7 days', normalRange: 'No beta-thalassaemia mutation detected', preparationInstructions: 'No fasting required.', description: 'Detects thalassaemia mutations. Essential in India given high carrier prevalence. Important pre-marital test.' },
  { name: 'G6PD Deficiency Test', category: 'Genetic Tests', sampleType: 'Blood', popularityFlag: 'Advanced', price: 999, estimatedReportTime: '24-48 hours', normalRange: 'Normal 4.6-13.5 U/g Hb; Deficient < 3.0', preparationInstructions: 'No fasting. Avoid specimen collection during haemolytic episode.', description: 'Detects G6PD enzyme deficiency causing haemolytic anaemia triggered by infections and certain drugs.' },

  // ── IMAGING & RADIOLOGY ──────────────────────────────────────────────────────
  { name: 'Chest X-Ray (PA View)', category: 'Imaging & Radiology', sampleType: 'N/A', popularityFlag: 'Common', price: 350, estimatedReportTime: '30 minutes', normalRange: 'Normal cardiothoracic ratio < 50%; Clear lung fields', preparationInstructions: 'Remove jewellery and metal objects.', description: 'Evaluates heart, lungs, ribs, and mediastinum. Standard pre-operative screen and pneumonia diagnosis.', tags: ['X-ray','chest','lung'] },
  { name: 'X-Ray Spine (Lumbar)', category: 'Imaging & Radiology', sampleType: 'N/A', popularityFlag: 'Common', price: 450, estimatedReportTime: '30 minutes', normalRange: 'Normal alignment; disc spaces maintained', preparationInstructions: 'Remove metal objects. Inform if pregnant.', description: 'Evaluates lumbar vertebrae, disc spaces, and alignment. Used for back pain and spondylosis.' },
  { name: 'Ultrasound Abdomen & Pelvis', category: 'Imaging & Radiology', sampleType: 'N/A', popularityFlag: 'Common', price: 799, estimatedReportTime: '30-45 minutes', normalRange: 'No focal lesions; normal organ size and echogenicity', preparationInstructions: 'Full bladder for pelvic. Fast 4-6 hours for abdomen.', description: 'Evaluates liver, gallbladder, pancreas, kidneys, spleen, and pelvic organs.', tags: ['USG','ultrasound','abdomen'] },
  { name: 'CT Scan Abdomen (with contrast)', category: 'Imaging & Radiology', sampleType: 'N/A', popularityFlag: 'Advanced', price: 3999, estimatedReportTime: '1-2 hours', normalRange: 'No focal lesions or lymphadenopathy', preparationInstructions: 'Fast 4-6 hrs. Inform of contrast dye allergy or kidney disease.', description: 'High-resolution cross-sectional imaging of abdominal organs for masses, trauma, and appendicitis.', tags: ['CT','abdomen','radiology'] },
  { name: 'CT Scan Brain (Plain)', category: 'Imaging & Radiology', sampleType: 'N/A', popularityFlag: 'Common', price: 3499, estimatedReportTime: '45 minutes', normalRange: 'No haemorrhage; no midline shift; normal grey/white matter', preparationInstructions: 'Remove metal objects.', description: 'Evaluates intracranial haemorrhage, stroke, hydrocephalus rapidly. First-line neuroimaging in emergency.' },
  { name: 'MRI Brain (with & without contrast)', category: 'Imaging & Radiology', sampleType: 'N/A', popularityFlag: 'Advanced', price: 4999, estimatedReportTime: '45-90 minutes', normalRange: 'No abnormal signal intensity', preparationInstructions: 'No metal implants. Claustrophobia check.', description: 'Superior soft tissue resolution for brain tumours, demyelination, epilepsy, and posterior fossa lesions.', tags: ['MRI','brain','tumour','neuro'] },
  { name: 'MRI Spine (Lumbar)', category: 'Imaging & Radiology', sampleType: 'N/A', popularityFlag: 'Advanced', price: 5499, estimatedReportTime: '45-90 minutes', normalRange: 'No disc herniation; normal cord signal', preparationInstructions: 'Declare all implants. No MRI for pacemakers.', description: 'Detailed imaging of vertebral discs, cord, and nerve roots. Standard for disc herniation and myelopathy.' },
  { name: 'Bone Density Scan (DEXA)', category: 'Imaging & Radiology', sampleType: 'N/A', popularityFlag: 'Advanced', price: 1999, estimatedReportTime: '20-30 minutes', normalRange: 'T-score >= -1.0 Normal; -1 to -2.5 Osteopenia; <= -2.5 Osteoporosis', preparationInstructions: 'No calcium supplements 24 hrs before.', description: 'Measures bone mineral density at hip and spine to diagnose osteoporosis and fracture risk.', tags: ['DEXA','bone density','osteoporosis'] },
  { name: 'Mammography', category: 'Imaging & Radiology', sampleType: 'N/A', popularityFlag: 'Common', price: 1299, estimatedReportTime: '30 minutes', normalRange: 'BI-RADS 1 or 2 = Normal/Benign', preparationInstructions: 'Avoid deodorant/lotion on chest. Schedule mid-cycle (day 7-14).', description: 'X-ray of breast tissue to screen for breast cancer. Recommended annually for women over 40.' },

  // ── HEALTH PACKAGES ──────────────────────────────────────────────────────────
  { name: 'Basic Health Checkup Package', category: 'Health Packages', sampleType: 'Multiple', popularityFlag: 'Common', price: 999, estimatedReportTime: '24-48 hours', normalRange: 'Multiple parameters - refer to report', preparationInstructions: 'Fast 10-12 hours. Bring all previous reports.', description: 'Foundational annual screen: CBC, blood sugar, lipid profile, liver, kidney, urine routine, and chest X-ray.', isPackage: true, packageTests: ['CBC','Fasting Blood Glucose','Lipid Profile','LFT','KFT','Urine Routine','Chest X-Ray'], recommendedAgeGroup: 'All ages 18+', tags: ['package','annual','basic'] },
  { name: 'Diabetes Management Package', category: 'Health Packages', sampleType: 'Multiple', popularityFlag: 'Common', price: 1499, estimatedReportTime: '24-48 hours', normalRange: 'HbA1c < 7% = Controlled; Multiple parameters', preparationInstructions: 'Fast 10-12 hours. Bring diabetes medications list.', description: 'Comprehensive diabetes monitoring: HbA1c, glucose, insulin, lipid profile, KFT, and urine microalbumin.', isPackage: true, packageTests: ['HbA1c','Fasting Glucose','PP Glucose','Insulin Fasting','Lipid Profile','KFT','Urine Microalbumin'], recommendedAgeGroup: 'Diabetic patients all ages', tags: ['package','diabetes'] },
  { name: 'Heart Health Package', category: 'Health Packages', sampleType: 'Multiple', popularityFlag: 'Common', price: 2499, estimatedReportTime: '48-72 hours', normalRange: 'Multiple cardiac parameters', preparationInstructions: 'Fast 10-12 hours. Avoid caffeine 12 hrs before ECG.', description: 'Cardiac risk assessment: ECG, lipid profile, troponin, homocysteine, CRP, blood pressure, and echo.', isPackage: true, packageTests: ['ECG','Lipid Profile','CRP','Homocysteine','Lp(a)','CBC','Fasting Glucose','2D Echo'], recommendedAgeGroup: 'Adults 30+', tags: ['package','cardiac','heart'] },
  { name: "Women's Wellness Package", category: 'Health Packages', sampleType: 'Multiple', popularityFlag: 'Common', price: 2999, estimatedReportTime: '48-72 hours', normalRange: 'Multiple parameters', preparationInstructions: 'Fast 8-10 hours. Schedule mid-cycle for hormone levels.', description: 'Comprehensive for women: CBC, hormones, thyroid, pap smear, mammography, DEXA, Vitamin D & B12.', isPackage: true, packageTests: ['CBC','Thyroid Profile','FSH & LH','Prolactin','Vitamin D','Vitamin B12','CA-125','Mammography'], recommendedAgeGroup: 'Women 25-65', tags: ['package','womens health','hormones'] },
  { name: 'Senior Citizen Health Package', category: 'Health Packages', sampleType: 'Multiple', popularityFlag: 'Common', price: 3999, estimatedReportTime: '48-72 hours', normalRange: 'Age-adjusted ranges - refer to report', preparationInstructions: 'Fast 10-12 hours. Bring all medications list.', description: 'Tailored for 60+ adults: CBC, diabetes, lipid, LFT, KFT, thyroid, cancer markers, ECG, echo, and DEXA.', isPackage: true, packageTests: ['CBC','HbA1c','Lipid Profile','LFT','KFT','Thyroid Profile','ECG','2D Echo','Vitamin D','DEXA','PSA or CA-125'], recommendedAgeGroup: 'Adults 60+', tags: ['package','senior','elderly'] },
  { name: 'Full Body Checkup (Premium)', category: 'Health Packages', sampleType: 'Multiple', popularityFlag: 'Common', price: 5999, estimatedReportTime: '48-72 hours', normalRange: '50+ parameters - refer to detailed report', preparationInstructions: 'Fast 10-12 hours. Carry photo ID. Schedule 4-6 hour appointment.', description: 'Most comprehensive health profile: 50+ parameters covering all organ systems, cancer markers, imaging, and cardiac.', isPackage: true, packageTests: ['CBC','LFT','KFT','Lipid Profile','Thyroid','HbA1c','Vitamins','Hormones','PSA/CA-125','CEA','ECG','Echo','X-Ray','USG Abdomen','Bone Density'], recommendedAgeGroup: 'Adults 35+', tags: ['package','full body','premium','comprehensive'] },
  { name: 'Youth Health Package (18-35)', category: 'Health Packages', sampleType: 'Multiple', popularityFlag: 'Common', price: 1299, estimatedReportTime: '24-48 hours', normalRange: 'Multiple parameters', preparationInstructions: 'Fast 8-10 hours.', description: 'Targeted for young adults: CBC, diabetes screen, lipid, thyroid, Vitamin D, STI screen, and urine.', isPackage: true, packageTests: ['CBC','Fasting Glucose','Lipid Profile','TSH','Vitamin D','Vitamin B12','HIV','HBsAg','HCV','Urine Routine'], recommendedAgeGroup: 'Adults 18-35', tags: ['package','youth','preventive'] },
];

async function seed() {
  try {
    const uri = process.env.MONGODB_URI;
    if (!uri || uri.length < 20) { console.error('MONGODB_URI missing in .env'); process.exit(1); }
    console.log('Connecting to MongoDB...');
    await mongoose.connect(uri, { serverSelectionTimeoutMS: 15000, family: 4 });
    console.log('Connected!');

    const existing = await LabTest.countDocuments();
    if (existing > 0) {
      console.log(`Clearing ${existing} existing lab tests...`);
      await LabTest.deleteMany({});
    }

    await LabTest.insertMany(TESTS);
    console.log(`\nSuccessfully seeded ${TESTS.length} lab tests!\n`);

    const byCategory = {};
    TESTS.forEach(t => { byCategory[t.category] = (byCategory[t.category] || 0) + 1; });
    Object.entries(byCategory).forEach(([cat, count]) => console.log(`  ${cat}: ${count} tests`));

    await mongoose.disconnect();
    console.log('\nDone! Refresh http://localhost:5173/lab-tests');
    process.exit(0);
  } catch (err) {
    console.error('Seeding failed:', err.message);
    if (err.errors) Object.entries(err.errors).forEach(([k, v]) => console.error(' -', k, ':', v.message));
    process.exit(1);
  }
}

seed();
